In [13]:

"""
Conformer_rl Analysis Example
=============================
View the notebook in Google Colab: https://drive.google.com/drive/folders/1WAnTv4SGwEQHHqyMcbrExzUob_mOfTcM?usp=sharing
≠
This notebook gives examples of how the analysis functions in conformer_rl can be used.
The example data (example_data1.pickle, example_data2.pickle and example_data3.pickle) were all
data taken from different evaluation episodes of an actual run.

The full API reference for the analysis module can be found at: 
"""
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="darkgrid")
from conformer_rl import analysis

In [14]:
"""
Test Dataset
"""
from pathlib import Path
from conformer_rl.datasets import QM9XYZDataset, create_qm9_dataloader

dataset_root = Path("dataset")
if not (dataset_root / "dsgdb9nsd.xyz").is_dir() and not any(dataset_root.glob("dsgdb9nsd_*.xyz")):
    dataset_root = Path("../dataset")

print("Using QM9 dataset root:", dataset_root.resolve())

dataset = QM9XYZDataset(
    root=str(dataset_root),
    target="mu",
    limit=1000,
)

data = dataset[0]

"""
Test Dataloader
"""
loader = create_qm9_dataloader(
    root=str(dataset_root),
    batch_size=32,
    shuffle=True,
    target=["homo", "lumo"],
)

batch = next(iter(loader))

"""
Peek Data
"""
print(data["x"].shape)
print(data["pos"].shape)
print(data["edge_index"].shape)
print(data["y"])
print(data["target_names"])

Using QM9 dataset root: /mnt/nfs/work/yoyo-0916/work/conformer-rl/dataset
torch.Size([5, 5])
torch.Size([5, 3])
torch.Size([2, 20])
tensor([[0.]])
['mu']


In [15]:
data = dataset[27]
data

Data(
  x=[6, 5],
  edge_index=[2, 30],
  edge_attr=[30, 1],
  y=[1, 1],
  pos=[6, 3],
  z=[6],
  properties=[1, 15],
  charges=[6, 1],
  frequencies=[12],
  molecule_id='gdb',
  qm9_index=28,
  property_names=[15],
  target_names=[1],
  property_dict={
    A=56.25048065185547,
    B=4.774409770965576,
    C=4.400879859924316,
    mu=0.0020000000949949026,
    alpha=26.1200008392334,
    homo=-0.2667999863624573,
    lumo=-0.11129999905824661,
    gap=0.15549999475479126,
    r2=266.81640625,
    zpve=0.03694299980998039,
    U0=-227.7987823486328,
    U=-227.79457092285156,
    H=-227.7936248779297,
    G=-227.8250732421875,
    Cv=12.147000312805176
  },
  smiles=[2],
  inchi=[2]
)

In [16]:
for key in data.keys:
    value = data[key]
    print("====", key, "====")
    if hasattr(value, "shape"):
        print("shape:", value.shape)
    print(value)

==== properties ====
shape: torch.Size([1, 15])
tensor([[ 5.6250e+01,  4.7744e+00,  4.4009e+00,  2.0000e-03,  2.6120e+01,
         -2.6680e-01, -1.1130e-01,  1.5550e-01,  2.6682e+02,  3.6943e-02,
         -2.2780e+02, -2.2779e+02, -2.2779e+02, -2.2783e+02,  1.2147e+01]])
==== charges ====
shape: torch.Size([6, 1])
tensor([[-0.1970],
        [ 0.0852],
        [ 0.0852],
        [-0.1970],
        [ 0.1118],
        [ 0.1118]])
==== pos ====
shape: torch.Size([6, 3])
tensor([[ 3.3712e-03, -3.1466e-02,  1.5721e-03],
        [-1.7132e-02,  1.1708e+00,  6.7644e-03],
        [ 1.2656e+00,  1.9972e+00, -7.7032e-05],
        [ 1.2451e+00,  3.1995e+00,  6.8128e-03],
        [-9.4690e-01,  1.7768e+00,  1.8527e-02],
        [ 2.1953e+00,  1.3912e+00, -1.0067e-02]])
==== y ====
shape: torch.Size([1, 1])
tensor([[0.0020]])
==== z ====
shape: torch.Size([6])
tensor([8, 6, 6, 8, 1, 1])
==== qm9_index ====
28
==== edge_attr ====
shape: torch.Size([30, 1])
tensor([[1.2025],
        [2.3893],
        [

In [17]:
for name, value in data.property_dict.items():
    print(name, value)

A 56.25048065185547
B 4.774409770965576
C 4.400879859924316
mu 0.0020000000949949026
alpha 26.1200008392334
homo -0.2667999863624573
lumo -0.11129999905824661
gap 0.15549999475479126
r2 266.81640625
zpve 0.03694299980998039
U0 -227.7987823486328
U -227.79457092285156
H -227.7936248779297
G -227.8250732421875
Cv 12.147000312805176


In [18]:
print(data.target_names)
print(data.y)

['mu']
tensor([[0.0020]])


In [19]:
for i in range(data.z.shape[0]):
    print("atom", i, "z =", int(data.z[i]), "pos =",data.pos[i].tolist(), "charge =", float(data.charges[i]))

atom 0 z = 8 pos = [0.003371224505826831, -0.031465861946344376, 0.001572062843479216] charge = -0.19698800146579742
atom 1 z = 6 pos = [-0.017131736502051353, 1.170814037322998, 0.0067644380033016205] charge = 0.08517300337553024
atom 2 z = 6 pos = [1.265557885169983, 1.9971940517425537, -7.703220035182312e-05] charge = 0.08517300337553024
atom 3 z = 8 pos = [1.2450706958770752, 3.1994659900665283, 0.006812752690166235] charge = -0.19698800146579742
atom 4 z = 1 pos = [-0.9469048380851746, 1.776781439781189, 0.018526678904891014] charge = 0.11181499809026718
atom 5 z = 1 pos = [2.1953442096710205, 1.3912137746810913, -0.010067391209304333] charge = 0.11181499809026718


In [20]:
for i in range(data.edge_index.shape[1]):
    src = int(data.edge_index[0, i])
    dst = int(data.edge_index[1, i])
    dist = float(data.edge_attr[i, 0])
    print(src, "->", dst, "distance =", dist)

0 -> 1 distance = 1.2024658918380737
0 -> 2 distance = 2.389263153076172
0 -> 3 distance = 3.4613242149353027
0 -> 4 distance = 2.04280948638916
0 -> 5 distance = 2.6132161617279053
1 -> 0 distance = 1.2024658918380737
1 -> 2 distance = 1.5258581638336182
1 -> 3 distance = 2.3892643451690674
1 -> 4 distance = 1.1098706722259521
1 -> 5 distance = 2.2234902381896973
2 -> 0 distance = 2.389263153076172
2 -> 1 distance = 1.5258581638336182
2 -> 3 distance = 1.2024662494659424
2 -> 4 distance = 2.223492383956909
2 -> 5 distance = 1.1098713874816895
3 -> 0 distance = 3.4613242149353027
3 -> 1 distance = 2.3892643451690674
3 -> 2 distance = 1.2024662494659424
3 -> 4 distance = 2.6132214069366455
3 -> 5 distance = 2.0428121089935303
4 -> 0 distance = 2.04280948638916
4 -> 1 distance = 1.1098706722259521
4 -> 2 distance = 2.223492383956909
4 -> 3 distance = 2.6132214069366455
4 -> 5 distance = 3.165945291519165
5 -> 0 distance = 2.6132161617279053
5 -> 1 distance = 2.2234902381896973
5 -> 2 dis

In [21]:
"""
Render a QM9 molecule with the analysis drawConformer viewer.
"""
from conformer_rl import analysis
from conformer_rl.datasets import qm9_data_to_rdkit_mol

qm9_mol = qm9_data_to_rdkit_mol(data)
view = analysis.drawConformer(qm9_mol, confId=0, size=(500, 300), style='stick')
view.setStyle({'stick': {'colorscheme': 'default'}})
view.setBackgroundColor('0xeeeeee')
view.zoomTo()
view.show()

Generating 3D view for conformer ID: 0
Displaying conformer ID: 0


3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [ ]:
from conformer_rl.datasets import find_qm9_samples_by_nonring_torsions

matches = find_qm9_samples_by_nonring_torsions(
    root="dataset",
    num_torsions=2,
    max_results=10,
)