In [1]:

"""
Conformer_rl Analysis Example
=============================
View the notebook in Google Colab: https://drive.google.com/drive/folders/1WAnTv4SGwEQHHqyMcbrExzUob_mOfTcM?usp=sharing
≠
This notebook gives examples of how the analysis functions in conformer_rl can be used.
The example data (example_data1.pickle, example_data2.pickle and example_data3.pickle) were all
data taken from different evaluation episodes of an actual run.

The full API reference for the analysis module can be found at: 
"""
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="darkgrid")
from conformer_rl import analysis

/mnt/nfs/work/yoyo-0916/miniconda3/envs/mycfmenv/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
"""
Test Dataset
"""
from pathlib import Path
from conformer_rl.datasets import QM9XYZDataset, create_qm9_dataloader

dataset_root = Path("dataset")
if not (dataset_root / "dsgdb9nsd.xyz").is_dir() and not any(dataset_root.glob("dsgdb9nsd_*.xyz")):
    dataset_root = Path("../dataset")

print("Using QM9 dataset root:", dataset_root.resolve())

dataset = QM9XYZDataset(
    root=str(dataset_root),
    target="mu",
    limit=1000,
)

data = dataset[0]

"""
Test Dataloader
"""
loader = create_qm9_dataloader(
    root=str(dataset_root),
    batch_size=32,
    shuffle=True,
    target=["homo", "lumo"],
)

batch = next(iter(loader))

"""
Peek Data
"""
print(data["x"].shape)
print(data["pos"].shape)
print(data["edge_index"].shape)
print(data["y"])
print(data["target_names"])

Using QM9 dataset root: /mnt/nfs/work/yoyo-0916/work/conformer-rl/dataset
torch.Size([5, 5])
torch.Size([5, 3])
torch.Size([2, 20])
tensor([[0.]])
['mu']


In [3]:
data = dataset[0]
data

Data(
  x=[5, 5],
  edge_index=[2, 20],
  edge_attr=[20, 1],
  y=[1, 1],
  pos=[5, 3],
  z=[5],
  properties=[1, 15],
  charges=[5, 1],
  frequencies=[9],
  molecule_id='gdb',
  qm9_index=1,
  property_names=[15],
  target_names=[1],
  property_dict={
    A=157.71180725097656,
    B=157.70997619628906,
    C=157.7069854736328,
    mu=0.0,
    alpha=13.210000038146973,
    homo=-0.38769999146461487,
    lumo=0.11710000038146973,
    gap=0.504800021648407,
    r2=35.36410140991211,
    zpve=0.044748999178409576,
    U0=-40.47893142700195,
    U=-40.4760627746582,
    H=-40.47511672973633,
    G=-40.49859619140625,
    Cv=6.468999862670898
  },
  smiles=[2],
  inchi=[2]
)

In [4]:
for key in data.keys:
    value = data[key]
    print("====", key, "====")
    if hasattr(value, "shape"):
        print("shape:", value.shape)
    print(value)

==== properties ====
shape: torch.Size([1, 15])
tensor([[ 1.5771e+02,  1.5771e+02,  1.5771e+02,  0.0000e+00,  1.3210e+01,
         -3.8770e-01,  1.1710e-01,  5.0480e-01,  3.5364e+01,  4.4749e-02,
         -4.0479e+01, -4.0476e+01, -4.0475e+01, -4.0499e+01,  6.4690e+00]])
==== property_dict ====
{'A': 157.71180725097656, 'B': 157.70997619628906, 'C': 157.7069854736328, 'mu': 0.0, 'alpha': 13.210000038146973, 'homo': -0.38769999146461487, 'lumo': 0.11710000038146973, 'gap': 0.504800021648407, 'r2': 35.36410140991211, 'zpve': 0.044748999178409576, 'U0': -40.47893142700195, 'U': -40.4760627746582, 'H': -40.47511672973633, 'G': -40.49859619140625, 'Cv': 6.468999862670898}
==== smiles ====
['C', 'C']
==== edge_attr ====
shape: torch.Size([20, 1])
tensor([[1.0920],
        [1.0920],
        [1.0919],
        [1.0919],
        [1.0920],
        [1.7831],
        [1.7831],
        [1.7832],
        [1.0920],
        [1.7831],
        [1.7832],
        [1.7831],
        [1.0919],
        [1.7831

In [5]:
for name, value in data.property_dict.items():
    print(name, value)

A 157.71180725097656
B 157.70997619628906
C 157.7069854736328
mu 0.0
alpha 13.210000038146973
homo -0.38769999146461487
lumo 0.11710000038146973
gap 0.504800021648407
r2 35.36410140991211
zpve 0.044748999178409576
U0 -40.47893142700195
U -40.4760627746582
H -40.47511672973633
G -40.49859619140625
Cv 6.468999862670898


In [6]:
print(data.target_names)
print(data.y)

['mu']
tensor([[0.]])


In [7]:
for i in range(data.z.shape[0]):
    print("atom", i, "z =", int(data.z[i]), "pos =",data.pos[i].tolist(), "charge =", float(data.charges[i]))

atom 0 z = 6 pos = [-0.012698136270046234, 1.0858041048049927, 0.008000995963811874] charge = -0.5356889963150024
atom 1 z = 1 pos = [0.0021504159085452557, -0.006031317636370659, 0.0019761202856898308] charge = 0.13392099738121033
atom 2 z = 1 pos = [1.0117307901382446, 1.463751196861267, 0.00027657480677589774] charge = 0.13392199575901031
atom 3 z = 1 pos = [-0.5408150553703308, 1.4475265741348267, -0.876643717288971] charge = 0.1339229941368103
atom 4 z = 1 pos = [-0.5238136053085327, 1.4379326105117798, 0.90639728307724] charge = 0.1339229941368103


In [8]:
for i in range(data.edge_index.shape[1]):
    src = int(data.edge_index[0, i])
    dst = int(data.edge_index[1, i])
    dist = float(data.edge_attr[i, 0])
    print(src, "->", dst, "distance =", dist)

0 -> 1 distance = 1.091952919960022
0 -> 2 distance = 1.091951608657837
0 -> 3 distance = 1.0919463634490967
0 -> 4 distance = 1.0919475555419922
1 -> 0 distance = 1.091952919960022
1 -> 2 distance = 1.7831196784973145
1 -> 3 distance = 1.7831474542617798
1 -> 4 distance = 1.7831566333770752
2 -> 0 distance = 1.091951608657837
2 -> 1 distance = 1.7831196784973145
2 -> 3 distance = 1.7831575870513916
2 -> 4 distance = 1.7831482887268066
3 -> 0 distance = 1.0919463634490967
3 -> 1 distance = 1.7831474542617798
3 -> 2 distance = 1.7831575870513916
3 -> 4 distance = 1.7831478118896484
4 -> 0 distance = 1.0919475555419922
4 -> 1 distance = 1.7831566333770752
4 -> 2 distance = 1.7831482887268066
4 -> 3 distance = 1.7831478118896484
